version: "3"
networks:
  dem:
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amongoass_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dem
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORTS: 80
    ports:
      - "5005:80"
    depends_on:
      - postgres
    networks:
      - dem
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_app
    volumes:
      - .:/postgres_python
    depends_on:
      - postgres
    networks:
      - dem